### ISSUE TITLE
시간표에서 과목 시간 정보 대신 강의실 위치로 수정

### ISSUE THREAD

**Issue by junglesub** [handong-life/college-timetable#52]
### 기존
![image](https://user-images.githubusercontent.com/42944002/150292858-3fe2c90d-867e-4308-bf38-4a385e196235.png)

### 추천
![image](https://user-images.githubusercontent.com/42944002/150292990-45ed1544-fc81-4c8b-b00e-f644556d9cb0.png)

지금은 시간표에서 과목의 시간 정보 (요일과 분반 | eg. 화2,금2)에 대한 정보가 나옵니다.
하지만 시간 정보보다는 수업 강의실 위치가 더 중요할 것 같다는 생각이 들었는데 여러분의 의견이 궁금합니다.

**Comment by yeob-yi** [comment]
좋은 것 같아요 !!
시간표에서 과목별 학점까지 볼 수 있으면 더 좋을꺼같아요 ,,!!!

**Comment by zoomkoding** [comment]
오 좋은 의견 같습니다 👍 
시간표에서 위치로 요일 정보는 알수 있으니까 다른 정보를 보여줘도 괜찮을 듯 합니다:) 
다만 같은 과목 아이템이 떨어져있다 보니 색을 추가해서 같은 과목은 같은 색을 가지게 하는 것도 좋겠네요!

**Comment by shine-jung** [comment]
좋은거 같습니다!
혹시 제가 이 이슈를 맡아서 작업해도 될까요??
